# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('direccion', models.CharField(max_length=120)),
                ('categoria', models.IntegerField()),
                ('url', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alojamiento_Seleccionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=56)),
                ('fecha', models.CharField(max_length=120)),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Alojamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField()),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Alojamiento')),
            ],
        ),
        migrations.CreateModel(
            name='CSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=56)),
                ('titulo', models.CharField(max_length=56)),
                ('tamannoFuente', models.FloatField()),
                ('colorFondo', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Alojamiento')),
            ],
        ),
    ]
