# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='categoria',
            field=models.CharField(max_length=12),
        ),
    ]
