# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0003_auto_20160518_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alojamiento_seleccionado',
            old_name='alojamiento',
            new_name='alojamiento_id',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='alojamiento',
            new_name='alojamiento_id',
        ),
        migrations.RenameField(
            model_name='imagen',
            old_name='alojamiento',
            new_name='alojamiento_id',
        ),
    ]
