# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0004_auto_20160519_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento_seleccionado',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
