# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0005_auto_20160519_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento_seleccionado',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
